### PR TITLE
Add dpi parameter to show()

### LINKED ISSUE #9: Plotting speed
The sample script takes 30 seconds to be executed. That's inconvenient.

```python
import smartplot
smartplot.addplot('data2.csv', number=4)
smartplot.axes(r"1", r"2")
smartplot.show()
```

```sh
$ time python speedtest.py
real	0m33.984s
```

### PR DESCRIPTION
**Pull request by ghost**
This should resolve #9
Plotting speed increased by 6x

### CODE REVIEW

**Comment by gkorepanov** [comment]
Reasonable alteration.

**Comment by gkorepanov** [comment]
Will resolve merging conflict after having a good deal of sleep.

**Comment by uteshevia** [comment]
I could do this)

**Comment by gkorepanov** [comment]
Merged into master.

**Pull request closed without merging**
